# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586ff3abf337edcfeb3596c7d9354d523cba98dcc693328405fc6424cfddaaa8ad79df2ae1d721eb2900a45f730085813a2d55614c77f70560b5c8fbd5f9e876

test:
  secret_key_base: b1cea7097da29323fe8e60136909f1a39e9e9072eeedba17b5399916c8598b5443ba4bae84dbbc2ce37e0c140343261b32ada38abcedcac82001962e2518b3a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
